twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/errors': errors
framework:
    error_controller: 'App\Controller\ExceptionController::showException'

when@test:
    twig:
        strict_variables: true,
        form_themes: ['bootstrap_5_layout.html.twig']
